---

- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Configure nginx config
  ansible.builtin.template:
    src: node-exporter.j2
    dest: /etc/nginx/sites-available/node-exporter
    owner: root
    group: root
    mode: '0644'
    # validate: /usr/sbin/nginx -t -c %s
  notify: Restart nginx

- name: Enable node-exporter site in nginx
  ansible.builtin.file:
    src: /etc/nginx/sites-available/node-exporter
    dest: /etc/nginx/sites-enabled/node-exporter
    owner: root
    group: root
    state: link

- name: Disable default site in nginx
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
